add bounty to rebase
OlympusDAO/olympus-contracts pull request #116
Opened 2021-11-30 06:43 UTC by olyzeus

recompensate user, or compensate keeper, for gas cost of rebase() function.

2021-12-06 21:28 UTC, ind-igo approved these changes

2021-12-06 21:34 UTC, olyzeus commented on contracts/Staking.sol
> +        if (rebase() && address(distributor) != address(0)) {
addressed

2021-12-06 21:34 UTC, olyzeus commented on contracts/Staking.sol
> +            if (rebase() && address(distributor) != address(0)) {
addressed

2021-12-06 21:38 UTC, olyzeus commented on contracts/Staking.sol
> +            if (contractBalance() <= totalStaked().add(bounty)) {
addressed. contractBalance() and totalStaked() removed, replaced by local vars querying their values

2021-12-06 21:43 UTC, olyzeus commented on contracts/StakingDistributor.sol
> +                } else {
bounty check removed. struct addition should be queued for future update (distributor can be replaced)

2021-12-07 04:00 UTC, ind-igo requested changes

2021-12-07 06:03 UTC, ind-igo approved these changes

2021-12-07 20:40 UTC, merged